# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

commands: 
  build-and-start-app:
    steps:
      - run: 
          name: Set Use Go Modules env var.
          command: |
            echo "export GO111MODULE=on" >> $BASH_ENV export GO111MODULE=on
      
      #Need revel cmd runner
      - run: go get github.com/revel/revel
      - run: go get github.com/revel/cmd/revel
      - run: 
          name: Start Server in Background
          command: | 
            revel run revel-example
          background: true
      - run:
            name: Confirm Server Running
            command: |
              for i in `seq 1 10`;
              do
                nc -z localhost 9000 && echo Success && exit 0
                echo -n .
                sleep 1
              done
              echo Failed waiting for app && exit 1

jobs:
  build:
    docker:
      # specify the version 
      - image: circleci/golang:1.12-stretch-browsers

    working_directory: /go/src/revel-example
    steps:
      - checkout
      - build-and-start-app


workflows:
  version: 2
  build_web_tests:
    jobs:
      - build